---
title: "base_demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{base_demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fabldev)
library(ggplot2)
library(glue)
library(tictoc)
library(RecordLinkage)
```


```{r}
set.seed(42)
n1 <- 50
n2 <- 50
overlap <- n2/2
S = 50
burn = S * .1

show_progress <- T
fast = F
R <- NULL
all_patterns <- FALSE

m <- c(.05, .95, .05, .95, .05, .95, .05, .95, .05, .95)

u <- c(.99, .01, .99, .01, 
       1 - 1/30, 1/30, 1 - 1/12, 1/12, 1 - 1/15, 1/15)

levels <- c(2, 2, 2, 2, 2)

S <- 1000; burn <- S * .1
m_prior <- u_prior <- rep(1, length(m))
alpha <- beta <- 1

cd <- simulate_comparisons(m, u, levels, n1, n2, overlap, previous_matches = 5)
hash <- hash_comparisons(cd)
Ztrue <- cd$Ztrue

out <- vi_efficient(hash)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Ztrue, n1)


chain <- gibbs_efficient_brian(hash)
results_fabl <- estimate_links(chain$Z, n1)
eval_fabl <- evaluate_links(results_fabl$Z_hat, Ztrue, n1)
```

```{r}
df1 <- read.csv("../aistats24-code/data/febrl_4_B.csv") %>%
  arrange(rec_id) %>%
  mutate(rec_id = row_number())
df2 <- read.csv("../aistats24-code/data/febrl_4_B.csv") %>%
  arrange(rec_id) %>%
  mutate(rec_id = row_number())

n1 <- nrow(df1)
n2 <- nrow(df2)

Z_true <- seq(1:5000)
fields <- c(2, 3, 8, 10, 11)
types <- c("lv", "lv","bi", "bi", "bi")

cd <- compare_records(df1, df2, flds = fields, types = types,
                      breaks = c(0, .15))

hash <- hash_comparisons(cd, all_patterns = F)

out <- vi_efficient(hash)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Z_true, n1)
```


```{r}
data <- RecordLinkage::RLdata10000 %>%
  mutate(unique_id = RecordLinkage::identity.RLdata10000)

duplicates <- nrow(data) * .1

duplicated_ids <- data %>%
  filter(duplicated(unique_id)) %>%
  select(unique_id) %>%
  pull()

duplicated_records <- data %>%
  filter(unique_id %in% duplicated_ids) %>%
  arrange(unique_id) %>%
  mutate(rn = row_number())

duplicated_1 <- duplicated_records %>%
  filter(rn %% 2 == 0)

duplicated_2 <- duplicated_records %>%
  filter(rn %% 2 == 1)

non_duplicated_records <- data %>%
  filter(!(unique_id %in% duplicated_ids)) %>%
  mutate(rn = row_number())

non_duplicated_1 <- non_duplicated_records %>%
  filter(rn %% 2 == 0)

non_duplicated_2 <- non_duplicated_records %>%
  filter(rn %% 2 == 1)

df1 <- rbind(duplicated_1, non_duplicated_1)
df2 <- rbind(duplicated_2, non_duplicated_2)
n1 <- nrow(df1)
n2 <- nrow(df2)
Z_true <- rep(0, nrow(df1))
Z_true[1:duplicates] <- 1:duplicates

fields <- c(1, 3, 5, 6, 7)
types <- c("lv", "lv", "bi", "bi", "bi")

cd <- compare_records(df1, df2, flds = fields, types = types,
                      breaks = c(0, .15))

hash <- hash_comparisons(cd, all_patterns = F)

out <- vi_efficient(hash)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Z_true, n1)
```


