---
title: "base_demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{base_demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fabldev)
library(ggplot2)
```


```{r}
n1 <- 50
n2 <- 50
overlap <- n2/2
S = 50
burn = S * .1

show_progress <- T
fast = F
R <- NULL
all_patterns <- FALSE
threshold = 1e-5
tmax = 1000
fixed_iterations = NULL
b_init = TRUE
k = 1
tau = 1
seed = 0
fixed_u = F

m <- c(.05, .95, .05, .95, .05, .95, .05, .95, .05, .95)

u <- c(.99, .01, .99, .01, 
       1 - 1/30, 1/30, 1 - 1/12, 1/12, 1 - 1/15, 1/15)

levels <- c(2, 2, 2, 2, 2)

S <- 50; burn <- S * .1
m_prior <- u_prior <- rep(1, length(m))
alpha <- beta <- 1

cd <- simulate_comparisons(m, u, levels, n1, n2, overlap)
hash <- hash_comparisons(cd, method = c("vabl", "fabl"))
Ztrue <- cd$Ztrue

chain <- brl_efficient_serge(hash, S = S, burn = burn)
results <- estimate_links(chain$Z, n1)
results$Z_hat

chain <- gibbs_base(cd, S = S, burn = burn)
results <- estimate_links(chain, n1)

chain <- gibbs_efficient(hash, S = S, burn = burn)
results <- estimate_links(chain$Z, n1)
results$Z_hat

chain <- brl_efficient(hash, S = S, burn = burn)
results <- estimate_links(chain$Z, n1)
results$Z_hat

chain <- BRL::bipartiteGibbs(cd, nIter = S)
results <- estimate_links(chain$Z, n1)
results$Z_hat

out <- vi_efficient(hash)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Ztrue, n1)
out$t
elbo_vi <- data.frame(elbo = out$elbo_seq,
                      iter = 1:out$t, 
                      method = "vi")

out <- svi_efficient(hash, B = 10, k = 1, seed = 5)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Ztrue, n1)
out$t
elbo_svi <- data.frame(elbo = out$elbo_seq,
                      iter = seq_along(out$elbo_seq), 
                      method = "svi")

elbo_df <- rbind(elbo_vi, elbo_svi)

out <- fabldev:::svi_efficient2(hash, B = 10, holdout_size = 100, k = 1, seed = 42)
results <- vi_estimate_links(out, hash)
evaluate_links(results$Z_hat, Ztrue, n1)
out$t
elbo_svi <- data.frame(elbo = out$elbo_seq,
                      iter = seq_along(out$elbo_seq), 
                      method = "svi")

elbo_df <- rbind(elbo_vi, elbo_svi)

elbo_df %>% 
  ggplot() +
  aes(x = iter, y = elbo, color = method) +
  geom_line()
  

# chain <- gibbs_base_mm(cd, S = S, burn = burn)
# results <- estimate_links_mm(chain, n1)

#hash <- hash_comparisons(cd, all_patterns = T)
#View(hash$)

#cbind(out_vi$b_pi, out_svi$b_pi)
```


```{r}
Z_chain <- chain$Z
names(thing[thing>threshold]) %>% 

threshold <- .5
samps <- ncol(Z_chain)
probs <- apply(Z_chain, 1, function(x){
  table(x)/samps
})
probNoLink <- sapply(probs, function(x){
  1 - sum(x[names(x) != n1 + 1])
})
Z_hat <- rep(0, n2)
maxProbOption <- sapply(probs, function(x){
  names(which.max(x))
}) %>% 
  as.numeric()
probmaxProbOption <- sapply(probs, function(x){
  max(x)
})
maxProbOptionIsLink <- maxProbOption < n1 + 1

Z_hat[probmaxProbOption > threshold] <- maxProbOption[probmaxProbOption > threshold]

  if (resolve == T){

    double_matches <- Z_hat[duplicated(Z_hat) & Z_hat > 0]
    if (lR == Inf){
      to_resolve <- unlist(lapply(double_matches, function(x){
        dfB_options <- which(Z_hat == x)
        dfB_probs <- probMaxProbOption[dfB_options]
        non_matches <- dfB_options[-which.max(dfB_probs)]
        non_matches
      }))
      Z_hat[to_resolve] <- 0
    } else {
      to_resolve <- unlist(lapply(double_matches, function(x){
        dfB_options <- which(Z_hat == x)
        dfB_options
      }))
      Z_hat[to_resolve] <- -1
    }
  }

thing1 <- matrix(c(1, 2, 3, 4), 2, 2)
thing2 <- matrix(c(1, 2, 3, 4), 2, 2)
thing3 <- matrix(c(1, 2, 3, 4), 2, 2)
thing <- list(thing1, thing2, thing3)

thing %>% 
  Reduce(`+`, .)
```

